

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';



export const ACTIVATE_POPUP = 'ACTIVATE_POPUP';
export const DIACTIVATE_POPUP = 'DIACTIVATE_POPUP';

